### ISSUE TITLE
Clustering implementation

### ISSUE THREAD

**Issue by SebAshton** [openstack-ansible-galaxy/rabbitmq#21]
I've just tried spinning up a HA RabbitMQ cluster using this ansible script. In order to get it to successfully cluster I had to manually intervene a number of times;

> **Issue** `Starting message broker rabbitmq-server` upon ` Start and enable RabbitMQ server`
> **Fix** `rm -rf /var/lib/rabbitmq/mnesia` and `kill -9 <rabbitmq_pid>`s

This enabled me to successfully provision the box.

> **Issue** My nodes couldn't resolve each other
> **Fix** Nano `/etc/hosts` and manually add the IPs

And Lastly;

> **Issue** My new nodes weren't clustered
> **Fix** `rabbitmqctl stop_app` then `rabbitmqctl join_cluster rabbit@<my_other_hostname>`

I was then able to `service rabbitmq-server start` and all was right in the world again. Just worried this isn't repeatable.

Am I missing something here, or would you accept a PR to fix?

**Comment by davidwinter** [comment]
It appears as though this is partly down to the configuration template files using `ansible_hostname`. For some servers where this is not an FQDN that actually resolves to anything, there is the requirement that the value is added to the `/etc/hosts` file manually. This can be done using the following:

```yml
pre_tasks:
    - name: Add cluster nodes to /etc/hosts file
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
        state: present
      with_items: "{{ ansible_play_hosts }}"
      when: ansible_default_ipv4.address != hostvars[item]['ansible_default_ipv4']['address']
```

However, even with this, when attempting to start RabbitMQ for the first time at the step `Start and enable RabbitMQ server`, it fails. In the log:

```
# cat /var/log/rabbitmq/startup_log
ERROR: node with name "rabbit" already running on "my-rabbitmq-node-three"

DIAGNOSTICS
===========

nodes in question: ['rabbit@my-rabbitmq-node-three']

hosts, their running nodes and ports:
- my-rabbitmq-node-three: [{rabbit,47784},
                                      {rabbitmqprelaunch6519,45722},
                                      {rabbitmqctl6543,46284}]

current node details:
- node name: 'rabbitmqprelaunch6519@my-rabbitmq-node-three'
- home dir: /var/lib/rabbitmq
- cookie hash: qH1oHdjasHjLVwsH+6SBMEiw==
```

This then requires the `rm -rf /var/lib/rabbitmq/mnesia` and `kill -9 <rabbitmq_pid>` for running PIDs and then various attempts at restarting the node.
